<?php

namespace app\modules\mvc;

use Yii;
use yii\base\BootstrapInterface;
use yii\console\Application;

class Module extends \yii\base\Module implements BootstrapInterface
{
    public $controllerNamespace = 'app\modules\mvc\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function bootstrap($app)
    {
        if ($app instanceof \yii\console\Application) {
            $this->controllerNamespace = 'app\modules\mvc\commands';
        }
    }
}